---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-demo-service
  namespace: backstage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-demo-service
  template:
    metadata:
      labels:
        app: backstage-demo-service
    spec:
      serviceAccountName: backstage-demo-sa
      containers:
        - name: backstage-demo-service
          image: container-image      
          args: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']    
          resources:            
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"