---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx3-deployment 
  namespace: nginx
  labels:
    app: nginx3  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3  
  template:
    metadata:
      labels:
        app: nginx3  
    spec:
      containers:
      - name: nginx3 
        image: container-image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi" 
            cpu: "250m" 
          limits:
            memory: "128Mi" 
            cpu: "500m" 