--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-sa-secret
  annotations:
    kubernetes.io/service-account.name: backstage-sa